name = "Kermit"
uuid = "41087bd6-378e-4ce9-beff-756e1368cb0a"
authors = ["Perro2110 <perrottamarco2011@gmail.com> and KingllamaTheIII <negrinilorenzo03@gmail.com>"]
version = "1.0.0-DEV"

[deps]
DecisionTree = "7806a523-6efd-50cb-b5f6-3fa6f1930dbb"
StringAnalysis = "b66b7d2f-f536-51df-9f97-4dfb9d27c005"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
